---
- name: Copy RHUI repo files to hosts missing them
  hosts: rhel9k8s
  become: true
  gather_facts: false

  tasks:
    - name: Check if redhat-rhui.repo exists
      ansible.builtin.stat:
        path: /etc/yum.repos.d/redhat-rhui.repo
      register: rhui_repo_stat
      
    - name: Check if redhat-rhui-beta.repo.disabled file exists
      ansible.builtin.stat:
        path: /etc/yum.repos.d/redhat-rhui-beta.repo.disabled
      register: rhui_beta_repo_stat

    - name: Check if redhat-rhui-client-config.repo file exists
      ansible.builtin.stat:
        path: /etc/yum.repos.d/redhat-rhui-client-config.repo
      register: rhui_client_config_repo_stat

    - name: Fetch redhat-rhui.repo file
      ansible.builtin.fetch:
        src: /etc/yum.repos.d/redhat-rhui.repo
        dest: "./files/{{ inventory_hostname }}/etc/yum.repos.d/"
        flat: no
      when: rhui_repo_stat.stat.exists

    - name: Fetch redhat-rhui-beta.repo.disabled file
      ansible.builtin.fetch:
        src: /etc/yum.repos.d/redhat-rhui-beta.repo.disabled
        dest: "./files/{{ inventory_hostname }}/etc/yum.repos.d/"
        flat: no
      when: rhui_beta_repo_stat.stat.exists

    - name: Fetch redhat-rhui-client-config.repo file
      ansible.builtin.fetch:
        src: /etc/yum.repos.d/redhat-rhui-client-config.repo
        dest: "./files/{{ inventory_hostname }}/etc/yum.repos.d/"
        flat: no
      when: rhui_client_config_repo_stat.stat.exists
      
    - name: Check if redhat-rhui-beta.repo.disabled exists #### ------ NOW COPY from k8s-worker01 to host missing it-----
      ansible.builtin.copy:
        src: "/etc/yum.repos.d/redhat-rhui.repo"
        dest: /etc/yum.repos.d/redhat-rhui.repo
        owner: root
        group: root
        mode: '0644'
        remote_src: yes
      when: not rhui_repo_stat.stat.exists
      delegate_to: k8s-worker01

    - name: Copy redhat-rhui-beta.repo.disabled from k8s-worker01 to hosts missing it
      ansible.builtin.copy:
        src: "/etc/yum.repos.d/redhat-rhui-beta.repo.disabled"
        dest: /etc/yum.repos.d/redhat-rhui-beta.repo.disabled
        owner: root
        group: root
        mode: '0644'
        remote_src: yes
      when: not rhui_beta_repo_stat.stat.exists
      delegate_to: k8s-worker01

    - name: Copy redhat-rhui-client-config.repo from k8s-worker01 to hosts missing it
      ansible.builtin.copy:
        src: "/etc/yum.repos.d/redhat-rhui-client-config.repo"
        dest: /etc/yum.repos.d/redhat-rhui-client-config.repo
        owner: root
        group: root
        mode: '0644'
        remote_src: yes
      when: not rhui_client_config_repo_stat.stat.exists
      delegate_to: k8s-worker01
