---
- name: Fetch RHUI repo files from RHUI-enabled servers
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Check if redhat-rhui.repo file exists
      ansible.builtin.stat:
        path: /etc/yum.repos.d/redhat-rhui.repo
      register: rhui_repo_stat

    - name: Check if redhat-rhui-beta.repo.disabled file exists
      ansible.builtin.stat:
        path: /etc/yum.repos.d/redhat-rhui-beta.repo.disabled
      register: rhui_beta_repo_stat

    - name: Check if redhat-rhui-client-config.repo file exists
      ansible.builtin.stat:
        path: /etc/yum.repos.d/redhat-rhui-client-config.repo
      register: rhui_client_config_repo_stat

    - name: Fetch redhat-rhui.repo file
      ansible.builtin.fetch:
        src: /etc/yum.repos.d/redhat-rhui.repo
        dest: "files/{{ inventory_hostname }}/etc/yum.repos.d/"
        flat: no
      when: rhui_repo_stat.stat.exists

    - name: Fetch redhat-rhui-beta.repo.disabled file
      ansible.builtin.fetch:
        src: /etc/yum.repos.d/redhat-rhui-beta.repo.disabled
        dest: "files/{{ inventory_hostname }}/etc/yum.repos.d/"
        flat: no
      when: rhui_beta_repo_stat.stat.exists

    - name: Fetch redhat-rhui-client-config.repo file
      ansible.builtin.fetch:
        src: /etc/yum.repos.d/redhat-rhui-client-config.repo
        dest: "files/{{ inventory_hostname }}/etc/yum.repos.d/"
        flat: no
      when: rhui_client_config_repo_stat.stat.exists
