---
# System Setup (RHEL registration, SELinux, Swap, Sysctl, etc.)
- name: Register RHEL subscription
  community.general.redhat_subscription:
    username: "{{ myusername }}"
    password: "{{ mypassword }}"
    auto_attach: true
    state: present

- name: Enable required RHEL repos
  ansible.builtin.shell: |
    subscription-manager repos --enable=rhel-9-for-x86_64-baseos-rpms \
                               --enable=rhel-9-for-x86_64-appstream-rpms \
                               --enable codeready-builder-for-rhel-9-x86_64-rpms

- name: Ensure redhat.repo file is present
  ansible.builtin.stat:
    path: /etc/yum.repos.d/redhat-rhui.repo
  register: redhat_rhui_repo

- name: Fail if redhat.repo does not exist
  ansible.builtin.fail:
    msg: "redhat.repo file is missing. Repositories may not be enabled correctly."
  when: not redhat_rhui_repo.stat.exists

- name: Disable SELinux
  ansible.posix.selinux:
    state: disabled

- name: Disable swap
  ansible.builtin.shell: |
    swapoff -a
    sed -i.bak '/ swap /s/^/#/' /etc/fstab

- name: Load br_netfilter module immediately
  ansible.builtin.modprobe:
    name: br_netfilter
    state: present

- name: Ensure br_netfilter loads on boot
  ansible.builtin.copy:
    dest: /etc/modules-load.d/br_netfilter.conf
    content: "br_netfilter\n"
    mode: '0644'

- name: Configure sysctl for Kubernetes networking
  ansible.builtin.copy:
    dest: /etc/sysctl.d/k8s.conf
    content: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
      net.ipv4.ip_forward = 1
    mode: '0644'

- name: Apply sysctl settings
  command: sysctl --system
