---
- name: Setup Podman and Kubernetes on RHEL 9
  hosts: rhel9k8s
  become: true
  vars:
    myusername: ""
    mypassword: ""
    mystatus: "present"
  
  tasks:
    - name: Register and subscribe the system
      community.general.redhat_subscription:
        username: "{{ myusername }}"
        password: "{{ mypassword }}"
        state: "{{ mystatus }}"
        
    - name: Upgrading all RHEL packages to Latest
      ansible.builtin.dnf:
        name: '*'
        state: latest
        
    - name: Install pip if not present
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: present
      become: true
      loop:
        - python3
        - python3-pip
        - python3-firewall
        - firewalld

    - name: Import EPEL GPG key for RHEL 9
      ansible.builtin.rpm_key:
        state: present
        key: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-9
    
    - name: Install EPEL release on RHEL 9 repo required for Podman
      ansible.builtin.dnf:
        name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm"
        state: present
    
    - name: Ensure EPEL repo is enabled (optional but recommended)
      ansible.builtin.command: dnf config-manager --enable epel
      args:
        warn: false
      when: ansible_distribution == "RedHat" and ansible_distribution_major_version == "9"

    - name: Install Podman
      ansible.builtin.dnf:
        name: podman
        state: present

    - name: Disable SELinux required for Kubernetes components
      ansible.builtin.selinux:
        state: disabled

    - name: Add Kubernetes YUM repository
      ansible.builtin.yum_repository:
        name: kubernetes
        description: Kubernetes Repository
        baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
        gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg
        enabled: 1
        gpgcheck: 1

    - name: Install Kubernetes components
      ansible.builtin.dnf:
        name:
          - kubeadm
          - kubelet
          - kubectl
        state: present

    - name: Enable and start kubelet
      ansible.builtin.systemd:
        name: kubelet
        enabled: true
        state: started

    - name: Disable swap (required for Kubernetes)
      ansible.builtin.command:
        cmd: swapoff -a
      ignore_errors: true

    - name: Remove swap entry from fstab
      ansible.builtin.lineinfile:
        path: /etc/fstab
        regexp: '^.*swap.*'
        state: absent

    - name: Run a podman container - Nginx container using Podman
      ansible.builtin.command:
        cmd: podman run -d --name nginx-container -p 8080:80 nginx
      ignore_errors: true

    - name: Ensure Podman container is running
      ansible.builtin.command:
        cmd: podman ps -q --filter name=nginx-container
      register: podman_status

    - name: Debug podman status
      ansible.builtin.debug:
        msg: "Nginx Podman container running: {{ podman_status.stdout }}"

    - name: Wait for Podman container to be accessible via curl to check if the container is accessible
      ansible.builtin.wait_for:
        host: "{{ ansible_host }}"
        port: 8080
        delay: 10
        timeout: 30
        state: started
        msg: "Nginx container is not accessible"

    - name: Verify Nginx container is serving content (curl)
      ansible.builtin.command:
        cmd: curl -s http://localhost:8080
      register: curl_response
      retries: 5
      delay: 10
      until: curl_response.stdout == "Welcome to nginx!"
      ignore_errors: true

    - name: Debug curl response
      ansible.builtin.debug:
        msg: "Curl Response: {{ curl_response.stdout }}"

- name: Initialize Kubernetes master node
  hosts: k8smasters
  become: true
  tasks:
    - name: Check if Kubernetes master has been initialized
      ansible.builtin.stat:
        path: /etc/kubernetes/admin.conf
      register: master_initialized
      
    - name: Initialize kubeadm on master node
      ansible.builtin.command:
        cmd: kubeadm init --pod-network-cidr=10.244.0.0/16
      register: kubeadm_init
      when: not master_initialized.stat.exists
      ignore_errors: true

    - name: Set up kubeconfig for the master user
      ansible.builtin.copy:
        content: "{{ kubeadm_init.stdout_lines | join('\n') }}"
        dest: /home/{{ ansible_user }}/.kube/config
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0600'
      when: not master_initialized.stat.exists

    - name: Install Flannel CNI plugin
      ansible.builtin.command:
        cmd: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
      when: not master_initialized.stat.exists

- name: Join worker node to Kubernetes cluster
  hosts: k8sworkers
  become: true
  tasks:
    - name: Get list of nodes in the cluster
      ansible.builtin.command:
        cmd: kubectl get nodes -o=jsonpath='{.items[*].metadata.name}'
      register: existing_nodes
      ignore_errors: true
    
    - name: Check if worker node is already part of the cluster
      ansible.builtin.set_fact:
        worker_already_joined: "{{ ansible_hostname in existing_nodes.stdout.split(' ') }}"
      when: existing_nodes.stdout is defined
      
    - name: Join worker node to Kubernetes cluster
      ansible.builtin.command:
        cmd: kubeadm join <master_ip>:6443 --token <token> --discovery-token-ca-cert-hash sha256:<hash>
      when: not worker_already_joined and ansible_hostname != 'k8s-master01'

- name: Verify Kubernetes cluster status
  hosts: k8smasters
  become: true
  tasks:
    - name: Check Kubernetes node status
      ansible.builtin.command:
        cmd: kubectl get nodes
