---
- name: Setup Podman and Kubernetes on RHEL 9
  hosts: rhel9-servers
  become: true
  
  tasks:
    - name: Install EPEL repository required for Podman
      ansible.builtin.dnf:
        name: epel-release
        state: present

    - name: Install Podman
      ansible.builtin.dnf:
        name: podman
        state: present

    - name: Disable SELinux required for Kubernetes components
      ansible.builtin.selinux:
        state: disabled

    - name: Add Kubernetes YUM repository
      ansible.builtin.yum_repository:
        name: kubernetes
        description: Kubernetes Repository
        baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
        gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg
        enabled: 1
        gpgcheck: 1

    - name: Install Kubernetes components
      ansible.builtin.dnf:
        name:
          - kubeadm
          - kubelet
          - kubectl
        state: present

    - name: Enable and start kubelet
      ansible.builtin.systemd:
        name: kubelet
        enabled: true
        state: started

    - name: Disable swap (required for Kubernetes)
      ansible.builtin.command:
        cmd: swapoff -a
      ignore_errors: true

    - name: Remove swap entry from fstab
      ansible.builtin.lineinfile:
        path: /etc/fstab
        regexp: '^.*swap.*'
        state: absent

    - name: Run a podman container - Nginx container using Podman
      ansible.builtin.command:
        cmd: podman run -d --name nginx-container -p 8080:80 nginx
      ignore_errors: true

    - name: Ensure Podman container is running
      ansible.builtin.command:
        cmd: podman ps -q --filter name=nginx-container
      register: podman_status

    - name: Debug podman status
      ansible.builtin.debug:
        msg: "Nginx Podman container running: {{ podman_status.stdout }}"

- name: Initialize Kubernetes master node
  hosts: k8smaster
  become: true
  tasks:
    - name: Initialize kubeadm on master node
      ansible.builtin.command:
        cmd: kubeadm init --pod-network-cidr=10.244.0.0/16
      register: kubeadm_init
      ignore_errors: true

    - name: Set up kubeconfig for the master user
      ansible.builtin.copy:
        content: "{{ kubeadm_init.stdout_lines | join('\n') }}"
        dest: /home/{{ ansible_user }}/.kube/config
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0600'

    - name: Install Flannel CNI plugin
      ansible.builtin.command:
        cmd: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml

- name: Join worker node to Kubernetes cluster
  hosts: k8sworkers
  become: true
  tasks:
    - name: Join worker node to Kubernetes cluster
      ansible.builtin.command:
        cmd: kubeadm join <master_ip>:6443 --token <token> --discovery-token-ca-cert-hash sha256:<hash>
      when: ansible_hostname != 'master'

- name: Verify Kubernetes cluster status
  hosts: k8smaster
  become: true
  tasks:
    - name: Check Kubernetes node status
      ansible.builtin.command:
        cmd: kubectl get nodes
